
const en = {

  home: "Home",
  // users: "Users",
  // register: "Register",
  // login: "Login",

  // search: "Search",

  courses: "Courses",

  aboutUs: "About Us",
  pricing: "Pricing",
  contact: "Contact",
  About: "About Us",
  about: "Welcome to our platform, where we are passionate about empowering individuals to reach their full potential...",
  achievementsTitle: "Achievements",
  trustedByThousands: "Trusted by Thousands",
  trustedDesc: "We have successfully educated thousands of students, helping them gain essential skills and advance their careers globally.",
  awardWinningCourses: "Award-Winning Courses",
  awardDesc: "Our courses are recognized for their excellence and innovation in the industry, providing the latest skills and best teaching methodologies.",
  positiveFeedback: "Positive Student Feedback",
  feedbackDesc: "Our students consistently praise our courses for their depth, interactivity, and effectiveness in real-world applications.",
  industryPartnerships: "Industry Partnerships",
  partnershipsDesc: "We collaborate with top industry leaders, ensuring our students receive relevant, up-to-date education and career opportunities.",
  ourGoalsTitle: "Our Goals",
  providePracticalSkills: "Provide Practical Skills",
  practicalSkillsDesc: "Our goal is to equip students with real-world skills that are immediately applicable in their careers, ensuring success in the job market.",
  fosterProblemSolving: "Foster Creative Problem-Solving",
  problemSolvingDesc: "We encourage students to think critically, develop problem-solving skills, and approach challenges with confidence and creativity.",
  promoteCollaboration: "Promote Collaboration and Community",
  collaborationDesc: "Learning is more effective in a supportive environment. We foster a strong community where students and professionals can connect, share knowledge, and grow together.",
  stayAhead: "Stay Ahead of the Curve",
  aheadDesc: "The digital landscape is constantly evolving, and our courses are designed to keep students updated with the latest industry trends and technologies.",
  futureTitle: "Together, let's shape the future of digital innovation",
  futureDesc: "Join us on this exciting journey and unlock your full potential in the world of design and development.",
  joinNow: "Join Now",
  title: "List Page",
  switchTo: "Switch to Arabic",
  theme: "Current Theme",
  light: "Light",
  back: "Back to home",
  fullName: 'Full Name',
  email: 'Email',
  password: 'Password',
  confirm: 'Confirm Password',
  dark: "Dark",
  users: "Users",
  register: "Register",
  login: "Login",
  logout: "Logout",
  // contact us
  firstName: 'First Name',
  lastName: 'Last Name',
  phone: 'Phone',
  subject: 'Subject',
  message: 'Message',
  send: 'Send Your Message',
  // Footer
  benefits: "Benefits",
  ourCourses: "Our Courses",
  testimonials: "Testimonials",
  faq: "FAQ",
  company: "Company",
  achievements: "Achievements",
  blog: "Blog",
  contactUs: "Contact Us",
  ourGoals: "Our Goals",
  socialProfiles: "Social Profiles",
  ourTeam: "Our Team",
  // log in page
  logIn: "Log in",
  loginWithGoogle: "Login with Google",
  dontHaveAccount: "Don't have an account?",
  signUp: "Sign up",
  forgotPassword: "Forgot Password?",
  welcomeBack: "Welcome back!",
  rememberMe: "remember me",
  or: 'or',
  // register page
  signUpToYourAccount: "Sign up to your account",
  alreadyHaveAccount: "Already have an account?",
  registerAsAdmin: "Register as Admin",
  adminSecretNumber: "Admin Secret Number",
  ageeTerms: "I agree to the terms and conditions",
  signUpWithGoogle: "Sign up with Google",
  alreadyAccount: "Already have an account?",
  // about us

  search: "Search",
  footer: "All rights reserved @ © Mahmoud 2025",
  next: "Next",
  previous: "Previous",
  addToFavorites: "Add to Favorites",
  viewDetails: "View Details",
  favorites: "Favorites",


};
export default en;
